name: Create new hack

on:
  workflow_dispatch:
    inputs:
      hackName:
        description: The name of the hack you want to create
        required: true
        default: YetAnotherHack
      numberOfChallenges:
        description: The number of challenges you want
        required: true
        default: 3
jobs:
  checklinks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print Directory Structure
        run: |
           ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
      - name: Generate WhatTheHack template stubs
        run: ${{ github.workspace }}/.github/workflows/createWthTemplate.sh